### ISSUE TITLE
Cucumber ocassionally creates empty log files which break the output parsing and cause a non 0 exit code

### ISSUE THREAD

**Issue by vsiakka** [midniteio/multi-cuke#55]
It seems to happen randomly for any given test. I have seen it a few times with the unit tests.

**Comment by midniteio** [comment]
I believe this was due to two TestHandlers being called on the same json and creating a race condition. I've moved them to different files to alleviate this race condition and it seems to have cleared this up, https://github.com/midniteio/multi-cuke/pull/65/files#diff-d886ca1ffdc4de69bd21c4dfce1742bbR37
